ALTER TABLE `game_event` ADD `cat` INT NOT NULL;

UPDATE game_event SET cat = '1' WHERE eventEntry = '1';
UPDATE game_event SET cat = '1' WHERE eventEntry = '2';
UPDATE game_event SET cat = '1' WHERE eventEntry = '7';
UPDATE game_event SET cat = '1' WHERE eventEntry = '8';
UPDATE game_event SET cat = '1' WHERE eventEntry = '9';
UPDATE game_event SET cat = '1' WHERE eventEntry = '10';
UPDATE game_event SET cat = '1' WHERE eventEntry = '11';
UPDATE game_event SET cat = '1' WHERE eventEntry = '12';
UPDATE game_event SET cat = '3' WHERE eventEntry = '18';
UPDATE game_event SET cat = '3' WHERE eventEntry = '19';
UPDATE game_event SET cat = '3' WHERE eventEntry = '20';
UPDATE game_event SET cat = '3' WHERE eventEntry = '21';
UPDATE game_event SET cat = '1' WHERE eventEntry = '26';
UPDATE game_event SET cat = '1' WHERE eventEntry = '32';
UPDATE game_event SET cat = '1' WHERE eventEntry = '40';
UPDATE game_event SET cat = '1' WHERE eventEntry = '41';
UPDATE game_event SET cat = '3' WHERE eventEntry = '42';
UPDATE game_event SET cat = '3' WHERE eventEntry = '30';

ALTER TABLE game_event ADD COLUMN `name_loc8` varchar(255) NOT NULL AFTER `description`;
UPDATE game_event SET name_loc8='Огненный солнцеворот' WHERE eventEntry='1';
UPDATE game_event SET name_loc8='Зимний Покров' WHERE eventEntry='2';
UPDATE game_event SET name_loc8='Ярмарка Новолуния (Лес Тероккар)' WHERE eventEntry='3';
UPDATE game_event SET name_loc8='Ярмарка Новолуния (Элвиннский лес)' WHERE eventEntry='4';
UPDATE game_event SET name_loc8='Ярмарка Новолуния (Мулгор)' WHERE eventEntry='5';
UPDATE game_event SET name_loc8='Канун Нового года' WHERE eventEntry='6';
UPDATE game_event SET name_loc8='Лунный фестиваль' WHERE eventEntry='7';
UPDATE game_event SET name_loc8='Любовная лихорадка' WHERE eventEntry='8';
UPDATE game_event SET name_loc8='Сад чудес' WHERE eventEntry='9';
UPDATE game_event SET name_loc8='Детская неделя' WHERE eventEntry='10';
UPDATE game_event SET name_loc8='Неделя урожая' WHERE eventEntry='11';
UPDATE game_event SET name_loc8='Тыквовин' WHERE eventEntry='12';
UPDATE game_event SET name_loc8='Вторжение Элементалей' WHERE eventEntry='13';
UPDATE game_event SET name_loc8='Рыбомания Тернистой долины' WHERE eventEntry='14';
UPDATE game_event SET name_loc8='Рыбомания Тернистой долины' WHERE eventEntry='15';
UPDATE game_event SET name_loc8='Захват Добычи Арены Гурубаши' WHERE eventEntry='16';
UPDATE game_event SET name_loc8='Вторжение Плети' WHERE eventEntry='17';
UPDATE game_event SET name_loc8='К оружию! Альтеракская долина' WHERE eventEntry='18';
UPDATE game_event SET name_loc8='К оружию! Ущелье Песни Войны' WHERE eventEntry='19';
UPDATE game_event SET name_loc8='К оружию! Низина Арати' WHERE eventEntry='20';
UPDATE game_event SET name_loc8='К оружию! Око Бури' WHERE eventEntry='21';
UPDATE game_event SET name_loc8='Ворота Ахн’Кирадж' WHERE eventEntry='22';
UPDATE game_event SET name_loc8='Атака волков на Оргриммар (Первая группа)' WHERE eventEntry='23';
UPDATE game_event SET name_loc8='Атака волков на Оргриммар (Вторая группа)' WHERE eventEntry='24';
UPDATE game_event SET name_loc8='Защита столицы Оргриммар' WHERE eventEntry='25';
UPDATE game_event SET name_loc8='Хмельной фестиваль' WHERE eventEntry='26';
UPDATE game_event SET name_loc8='Вожди у Джин’Алаи' WHERE eventEntry='27';
UPDATE game_event SET name_loc8='Атака Мёртвого Легиона Орды на Штормград' WHERE eventEntry='28';
UPDATE game_event SET name_loc8='Ночь' WHERE eventEntry='29';
UPDATE game_event SET name_loc8='Призыв к оружию на Берег Древних' WHERE eventEntry='30';
UPDATE game_event SET name_loc8='Даларан - Приглашение на Серебряный Авангард' WHERE eventEntry='31';
UPDATE game_event SET name_loc8='День пирата' WHERE eventEntry='32';
UPDATE game_event SET name_loc8='Вожди Джин’Алаи, Гаванил' WHERE eventEntry='33';
UPDATE game_event SET name_loc8='Рок концерт' WHERE eventEntry='34';
UPDATE game_event SET name_loc8='На грани Безумия, Гри’лек' WHERE eventEntry='35';
UPDATE game_event SET name_loc8='На грани Безумия, Хазза’рах' WHERE eventEntry='36';
UPDATE game_event SET name_loc8='На грани Безумия, Ренатаки' WHERE eventEntry='37';
UPDATE game_event SET name_loc8='На грани Безумия, Вушулай' WHERE eventEntry='38';
UPDATE game_event SET name_loc8='Вожди у Джин’Алаи, Чуло Безумный' WHERE eventEntry='39';
UPDATE game_event SET name_loc8='День мертвых' WHERE eventEntry='40';
UPDATE game_event SET name_loc8='Пиршество странников' WHERE eventEntry='41';
UPDATE game_event SET name_loc8='К оружию! Остров Завоеваний' WHERE eventEntry='42';
UPDATE game_event SET name_loc8='Hammerfall Under Attack' WHERE eventEntry='43';
UPDATE game_event SET name_loc8='Thrallmar Demon Attack' WHERE eventEntry='44';
UPDATE game_event SET name_loc8='Калуакское рыбоборье' WHERE eventEntry='45';
UPDATE game_event SET name_loc8='Падение Залазана' WHERE eventEntry='46';
UPDATE game_event SET name_loc8='Операция "Гномреган"' WHERE eventEntry='47';
UPDATE game_event SET name_loc8='Twilight’s Cult & Elemental Invasion' WHERE eventEntry='48';
UPDATE game_event SET name_loc8='Зимние подарки' WHERE eventEntry='49';
UPDATE game_event SET name_loc8='Январские события' WHERE eventEntry='50';
UPDATE game_event SET name_loc8='Февральские события' WHERE eventEntry='51';
UPDATE game_event SET name_loc8='Мартовские события' WHERE eventEntry='52';
UPDATE game_event SET name_loc8='Апрельские события' WHERE eventEntry='53';
UPDATE game_event SET name_loc8='Майские события' WHERE eventEntry='54';
UPDATE game_event SET name_loc8='Июньские события' WHERE eventEntry='55';
UPDATE game_event SET name_loc8='Июльские события' WHERE eventEntry='56';
UPDATE game_event SET name_loc8='Ангусские события' WHERE eventEntry='57';
UPDATE game_event SET name_loc8='Сентябрьские события' WHERE eventEntry='58';
UPDATE game_event SET name_loc8='Октябрьские события' WHERE eventEntry='59';
UPDATE game_event SET name_loc8='Ноябрьские события' WHERE eventEntry='60';
UPDATE game_event SET name_loc8='Декабрьские события' WHERE eventEntry='61';
UPDATE game_event SET name_loc8='World''s End Tavern - Perry Gatner Announce' WHERE eventEntry='62';
UPDATE game_event SET name_loc8='World''s End Tavern - Perry Gatner Standup Comedy' WHERE eventEntry='63';
UPDATE game_event SET name_loc8='Рыбалка (зимний сезон)' WHERE eventEntry='64';
UPDATE game_event SET name_loc8='Рыбалка (летний сезон)' WHERE eventEntry='65';
UPDATE game_event SET name_loc8='Рыбалка (00:00-06:00)' WHERE eventEntry='66';
UPDATE game_event SET name_loc8='Рыбалка (06:00-12:00)' WHERE eventEntry='67';
UPDATE game_event SET name_loc8='Рыбалка (12:00-18:00)' WHERE eventEntry='68';
UPDATE game_event SET name_loc8='Рыбалка (18:00-00:00)' WHERE eventEntry='69';
UPDATE game_event SET name_loc8='World''s End Tavern - L70ETC Concert Announce' WHERE eventEntry='70';
UPDATE game_event SET name_loc8='World''s End Tavern - L70ETC Concert' WHERE eventEntry='71';
UPDATE game_event SET name_loc8='Stormwind City - Stockades Jail Break' WHERE eventEntry='72';
UPDATE game_event SET name_loc8='Ночной эльф - ирокез' WHERE eventEntry='73';
UPDATE game_event SET name_loc8='Event boss Sargaron' WHERE eventEntry='81';
UPDATE game_event SET name_loc8='Event gameobject' WHERE eventEntry='82';
UPDATE game_event SET name_loc8='Смертельная гонка' WHERE eventEntry='85';
UPDATE game_event SET name_loc8='Event boss Amon' WHERE eventEntry='86';
UPDATE game_event SET name_loc8='Event boss Gor' WHERE eventEntry='87';
UPDATE game_event SET name_loc8='Event boss Nefertity' WHERE eventEntry='88';
UPDATE game_event SET name_loc8='Event boss Anubys' WHERE eventEntry='90';
UPDATE game_event SET name_loc8='Event boss Ra' WHERE eventEntry='91';
UPDATE game_event SET name_loc8='Арена первый сезон' WHERE eventEntry='124';
UPDATE game_event SET name_loc8='Арена второй сезон' WHERE eventEntry='125';
UPDATE game_event SET name_loc8='Арена третий сезон' WHERE eventEntry='126';
UPDATE game_event SET name_loc8='Арена четвёртый сезон' WHERE eventEntry='127';
UPDATE game_event SET name_loc8='Арена пятый сезон' WHERE eventEntry='128';
UPDATE game_event SET name_loc8='Арена шестой сезон' WHERE eventEntry='129';
UPDATE game_event SET name_loc8='Арена седьмой сезон' WHERE eventEntry='130';
UPDATE game_event SET name_loc8='Арена восьмой сезон' WHERE eventEntry='131';
UPDATE game_event SET name_loc8='Лотерея' WHERE eventEntry='132';
