CREATE TABLE IF NOT EXISTS `aowow_events` (
  `id` int(6) NOT NULL,
  `name_loc0` text NOT NULL,
  `name_loc8` text NOT NULL,
  `img` varchar(128) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `aowow_events` (`id`, `name_loc0`, `name_loc8`, `img`, `icon`) VALUES
(8, '<b>Love is in the Air</b> is an celebration of love and friendship during which players share gifts and candy, and the air is filled with perfume and cologne. This holiday is based on the real world customs of <a href="http://en.wikipedia.org/wiki/Valentine''''s_day" target="_blank">Valentine''''s Day.</a><br><br>Players can show their appreciation for their friends and faction leaders by collecting <a href="#" rel="item=49655"><font color="white">Lovely Charm</font></a> to create <a href="#" rel="item=49916"><font color="white">Lovely Charm Bracelet</font></a>, which can be turned in daily for rewards. The Crown Chemical Company has set up throughout the major cities of Azeroth, peddling perfumes, colognes, candy, and other seasonal goodies which can be purchased with <a href="#" rel="item=49927"><font color="white">Lovely Token</font></a> earned through completion of daily quests. But everything isn''''t exactly as it seems, and it''''s up to players to investigate these suspicious new goblins and their perfumed plague! <br><br>Completion of the twelve holiday achievements for <a href="#" rel="achievement=1693"><font color="gold">Fool For Love</font></a> will grant a player title - <font color="grey" face="cursive">Name</font> the Love Fool.', 'Русского описания для этого события пока нет, можете посмотреть пока на картинку справа =)', 'aryu.png', '8.jpg'),
(42, 'The battle for the Isle of Conquest grows intense. Greater honor is given to those who pledge sword to their liege and battle upon the Isle.', 'The battle for the Isle of Conquest grows intense. Greater honor is given to those who pledge sword to their liege and battle upon the Isle.', '', '42.jpg'),
(30, 'The battle for the Strand of the Ancients grows intense. Greater honor is given to those who pledge sword to their liege and battle upon the Strand.', '', '', '30.jpg'),
(2, 'The <b>Feast of Winter Veil</b> is a festive time of year during which players can sample delicious festive treats, playfully toss snowballs, and receive special holiday gifts! The Feast of Winter Veil is a reference to the end-of-year seasonal holiday of <a href="http://en.wikipedia.org/wiki/Christmas">Christmas</a>, featuring Greatfather Winter as an in-game version of <a href="http://en.wikipedia.org/wiki/Santa_Claus">Santa Claus</a>. <br />\r\n\r\nDuring the Feast of Winter Veil players are sent on various quests, involving such adventures as rescuing a <a href="/?npc=15664" target="_blank" rel="npc=15664">stolen reindeer</a> and defeating <a href="/?npc=13602" target="_blank" rel="npc=13602">The Abominable Greench</a> in order to retrieve a lost shipment of goodies! There are a number of special festival-only foods which players can purchase or prepare, ranging from delicious <a href="/?item=17197" tagret="_blank" rel="item=17197">Gingerbread Cookie</a> to the maybe-not-quite-so-delicious <a href="/?item=21215" tagret="_blank" rel="item=21215">Graccu''s Mince Meat Fruitcake</a>! As the festival nears its end, on the morning of December 25th (corresponding with Christmas Day) players can retrieve festive gifts from beneath tall, decorated trees found in Orgrimmar or Ironforge. These gifts contain seasonal, festival-only items and always includes a special item available only during that year''s festival - never again!\r\n<br />\r\n\r\nCompletion of the eleven holiday achievements specified by <a href="/?achievement=1691" tagret="_blank" rel="achievement=1691">Merrymaker</a> will grant a player title - Merrymaker <font color="grey">Name</font>.', 'Для данного события отсутствует описание', '', '2.jpg'),
(7, 'The Lunar Festival celebration takes place among the druids of <a href="/?zone=493" tagret="_blank">Moonglade</a>, where large festival camps feature fireworks launchers, festive lanterns, and exotic beams of light capable of teleporting players to capital cities. The Lunar Festival is a reference to the <a href="http://en.wikipedia.org/wiki/Chinese_New_Year" tagret="_blank">Chinese New Year</a> celebration, often called the Lunar New Year.<br/>\r\n\r\nDuring the Lunar Festival, players can visit ghostly Elders located throughout Azeroth and Northrend to give their respects and honor their ancestor''s spirit. In return, the Elder will reward the player with reputation and  <a href="/?item=21100" tagret="_blank" rel="item=21100">Coin of Ancestry</a>, which can be used to purchase seasonal attire and patterns from special vendors in Moonglade. These seasonal patterns teach skilled players to craft festival outfits (including suits and dresses) or explosive new fireworks! Player will also be called upon to defeat the corrupted demi-god <a href="/?npc=15467" tagret="_blank" rel="npc=15467">Omen</a> who stirs beneath the waters of Moonglade''s Lake Elune''ara.<br/>\r\n\r\nCompletion of all of the holiday achievements specified by  <a href="/?achievement=913" tagret="_blank" rel="achievement=913">To Honor One''s Elders</a> will grant a player title - Elder <font color="grey">Name</font>.', '', 'lunarperc.png', '7.jpg'),
(21, 'The battle for the Eye of the Storm grows intense. Greater honor is given to those who pledge sword to their liege and battle in the Eye.', '', '', '21.jpg'),
(18, 'The battle for Alterac Valley grows intense. Greater honor is given to those who pledge sword to their liege and battle in Alterac.', '', '', '18.jpg'),
(19, 'The battle for Warsong Gulch grows intense. Greater honor is given to those who pledge sword to their liege and battle in the Gulch.', '', '', '19.jpg'),
(20, 'Fight for Arathi Basin!', 'Не стихают бои в Низине Арати... Вечная слава отважным воинам, сражающимся на поле брани.', '', '20.jpg'),
(9, '<b>Noblegarden</b> is a festive time of year during which players hunt and collect carefully hidden colorfully painted eggs, which contain goodies such as festive clothing or delicious chocolates! Noblegarden is a reference to the more commercial aspects of the holiday of <a href="http://en.wikipedia.org/wiki/Easter" tagret="_blank">Easter</a>.<br><br>\r\n\r\nDuring Noblegarden, players can head out to starting towns and villages and hunt for <a href="/?item=45072" tagret="_blank" rel="item=45072">Brightly Colored Egg</a> which can be found hidden throughout the area. These eggs typically contain <a href="/?item=44791" tagret="_blank" rel="item=44791">Noblegarden Chocolate</a>, a currency used to purchase seasonal items, but players may get lucky and find a piece of gear from an assortment of seasonal equipment! Players might even uncover a <a href="/?item=44794" tagret="_blank" rel="item=44794">fuzzy little friend</a>!<br><br>\r\n\r\nPlayers also may acquire this holiday''s title, <font color="grey">Name</font> the Noble, by fulfilling all conditions of their faction''s respective meta-achievement <a href="/?achievement=2798" tagret="_blank" rel="achievement=2798">Noble Gardener</a> during the event.', '', 'rayg.png', '9.jpg'),
(10, 'Children''s Week is the time of year in which players focus on giving back to the children of the Horde and Alliance - innocent victims of the ongoing faction war (and their efforts versus Lich King). Orphaned children are available to be temporarily "adopted" from matrons and taken to visit various locations and people throughout Azeroth and Outland.<br><br>\r\n\r\nPlayers can visit <a href="/?npc=14450" tagret="_blank" rel="npc=14450">Orphan Matron Nightingale</a> in Stormwind, <a href="/?npc=14451" tagret="_blank" rel="npc=14451">Orphan Matron Battlewail</a> in Orgrimmar, <a href="/?npc=22819" tagret="_blank" rel="npc=22819">Orphan Matron Mercy</a> in Shattrath, or <a href="/?npc=34365" tagret="_blank" rel="npc=34365">Orphan Matron Aria</a> in Dalaran and make a child''s dream come true. The Horde can adopt Orc and Blood Elf orphans while the Alliance can adopt Human and Draenei orphans. Both factions are able to adopt their choice of either an <a href="/?faction=1105" tagret="_blank">The Oracles</a> or <a href="/?faction=1104" tagret="_blank">Frenzyheart Tribe</a> orphan. Upon completing the requested tasks from a chosen orphan, players will be rewarded with their choice of a cute, non-combat pet! These pets are available only during Children''s Week and only one per orphan<br><br>\r\n\r\nCompletion of the six holiday achievements specified by <a href="/?achievement=1793" tagret="_blank" rel="achievement=1793">For the Children</a> will grant a gender-specific player title - Matron <font color="grey">Name</font> or Patron <font color="grey">Name</font>.', '', '', '10.jpg'),
(11, 'The Harvest Festival is a small celebration held in honor of the fallen heroes of the Horde and Alliance. This holiday is based on real-world harvest festivals such as Korea''s Chuseok and the Chinese Mid-Autumn Festival.<br><br>\r\n\r\nSmall feast tables have been set up outside of Orgrimmar and Ironforge from which players can sample various harvest foods, and a nearby questgiver presents the task of honoring a fallen hero. Horde players will be sent to leave an object of tribute at the monument to Grom Hellscream in Ashenvale while Alliance players are sent to the tomb of Uther the Lightbringer in the Western Plaguelands. There are no other special items or quests related to this holiday.\r\n<br><br>\r\nThere is no special player title associated with this event.', '', '', '11.jpg'),
(32, 'World of Warcraft''s Pirates'' Day corresponds with the real world "holiday" of International Talk Like A Pirate Day. It''s the one day of the year to let your inner pirate out with a good, "Yarr!"<br><br>\r\n\r\nPlayers can travel out to Booty Bay and have a drink and dance with Dread Captain DeMeza and her pirate crew, located on the roof of the bank. Doing so will give you a sweet pirate costume buff that will last for 12 hours, even through death!\r\n<br><br>\r\nThere is no special player title associated with this event.', '', '', '32.jpg');